config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :clowns do
    resources :bookings
  end
  get "search", to: "search#search"
  get "clowns/:id/edit", to: "clowns#edit"
  patch "clowns/:id", to: "clowns#update"
  get "profile", to: "pages#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :clown
  belongs_to :user
end

app/models/clown.rb
class Clown < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :clowns
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :clowns, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.clown = Clown.find(params[:clown_id])
    authorize @booking
    if @booking.save!
      redirect_to profile_path, notice: "Le booking a été créé avec succès."
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params["id"])
    authorize @booking
  end

  def destroy
    @booking = Booking.find(params["id"])
    @booking.destroy
    redirect_to root_path, notice: "Le booking a été retiré avec succès.", status: :see_other
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :user, :clown)
  end
end

app/controllers/clown_controller.rb
class ClownController < ApplicationController

  def index
    @clowns = policy_scope(Clown)
  end

  def new
    @clown = Clown.new
    authorize @clown
  end

  def create
    @clown = Clown.new(params[:clown])
    @clown.save
    @clown.user = current_user
    authorize @clown
  end

  def show
    authorize @clown
  end

  def edit
    authorize @clown
  end
  def update
    authorize @clown
  end

  def destroy
    authorize @clown
  end
end

app/controllers/clowns_controller.rb
class ClownsController < ApplicationController
  def index
    @clowns = policy_scope(Clown)
  end

  def new
    @clown = Clown.new
    authorize @clown
  end

  def create
    @clown = Clown.new(clown_params)
    @clown.user = current_user
    authorize @clown
    if @clown.save
      redirect_to root_path, notice: "Le clown a été créé avec succès."
    else
      render :new
    end
  end

  def show
    @clown = Clown.find(params["id"])
    @booking = Booking.new
    authorize @clown
  end

  def destroy
    @clown = Clown.find(params["id"])
    @clown.destroy
    redirect_to root_path, notice: "Le clown a été retiré avec succès.", status: :see_other
    authorize @clown
  end

  def edit
    @clown = Clown.find(params[:id])
    authorize @clown
  end

  def update
    @clown = Clown.find(params[:id])
    @clown.update(clown_params)
    redirect_to clown_path(@clown)
    authorize @clown
  end

  private

  def clown_params
    params.require(:clown).permit(:username, :email, :personal_info, :password, :price, :category, :localisation, photos: [])
  end
end

app/controllers/concerns/reservation_controller.rb
class ReservationsController < ApplicationController

def show
  @reservation = Reservation.new
  @reservation.clown_name = @clown.username
  @reservation.clown_photo = @clown.photos.first.key
end

def reserve_clown
  @clown = current_user.clown
  @reservation = Reservation.new(reservation_params)
  @reservation.clown = Clown.find_by(username: params[:reservation][:clown_name])
  @reservation.save
  redirect_to profile_path
end

def create
  @clown = current_user.clown
  @reservation = Reservation.new(reservation_params)
  @reservation.clown = Clown.find_by(username: params[:reservation][:clown_name])
  if @reservation.save
    redirect_to profile_path
  else
    render :new
  end
end

private

  def reservation_params
    params.require(:reservation).permit(:date, :heure, :user_id, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @clowns = Clown.all
  end

  def show
  end

  def profile
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include Pundit

  def search
    @query = params[:query]
    # Implémentez ici votre logique de recherche en fonction de vos besoins
    if @query == "melissandre"
      redirect_to "/clown"
    else
    @results = Clown.where("column LIKE ?", "%#{@query}%")
    user.admin? ? scope.all : scope.where(user: user)
    render :search
    end
  end

  def show
    @model = Model.find(params[:id])
    authorize @model
    # Reste du code de l'action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/desroy.html.erb
<h1>Bookings#desroy</h1>
<p>Find me in app/views/bookings/desroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/clowns/destroy.html.erb
<h1>Delete a clown profile here</h1>

<%= form_with(model: clown, method: :delete, url: clown_path(clown)) do |form| %>
  <p>
    Êtes-vous sûr de vouloir détruire ce clown ?
  </p>
  <%= form.submit("Détruire le clown") %>
<% end %>

app/views/clowns/edit.html.erb
<h1>Modifier un clown</h1>
<p>Remplissez toutes les informations ci-dessous </p>
<br>
<br>

<%= simple_form_for @clown, class: "clown-form" do |f| %>
  <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Ajouter 3 photos"%>
  <%= f.input :username, label: "Nom du clown" %>
  <%= f.input :personal_info, label: "Informations du clown" %>
  <%= f.input :category, label: "Catégorie du clown" %>
  <%= f.input :localisation, label: "Localisation du clown" %>
  <%= f.input :price, label: "Prix par heure" %>
  <%= f.button :submit, "Modifier le clown", class: "blue-button" %>
<% end %>

app/views/clowns/new.html.erb
<h1>Register a new clown</h1>
<p>Please enter all informations asked below </p>
<br>
<br>

<%= simple_form_for @clown, class: "clown-form" do |f| %>
  <%= f.input :photos, as: :file, input_html: { multiple: true }, label:"Ajouter 3 photos" %>
  <%= f.input :username, label: "Nom du clown" %>
  <%= f.input :personal_info, label: "Informations du clown" %>
  <%= f.input :category, label: "Catégorie du clown" %>
  <%= f.input :localisation, label: "Localisation du clown" %>
  <%= f.input :price, label: "Prix par heure" %>
  <%= f.button :submit, "Créer le clown", class: "blue-button" %>
<% end %>

app/views/clowns/show.html.erb
<div class = "navbar" >
<div>
<%= link_to root_path do %>
<%= image_tag "SmilesForRent.png", class: "clown_logo" %>
<% end %>

<h1 class ="smile_name">SmilesForRent</h1>
</div>

<%= form_tag(search_path, method: :get, class: "search-form") do %>
  <%= text_field_tag(:query, params[:query], placeholder: "Rechercher...") %>
  <button type="submit" class="search-button">
    <i class="fa-solid fa-magnifying-glass" style="color: #FFFFFF;"></i>
  </button>
<% end %>

</div>

<br>

<div class="container" data-controller="popup confetti">
  <h2 class="clown-show-title"><%= @clown.username %></h2>
  <h5 class="clown-show-category"><%= @clown.category %></h5>

  <br>

  <i class="fas fa-heart"></i>
  <span class="favorite-text">Ajouter au favoris</span>

  <br>

  <div class="show-clown-image-container">
    <% @clown.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 400, width: 500, crop: :fill %>
    <% end %>
  </div>

  <br>
  <br>

  <div class="popup-clown">
    <h4>Merci d’avoir séléctioné <strong> "<%= @clown.username %>" </strong></h4>
    <p class="text-popup">un email pour confirmer votre réservation vous à été envoyé.</p>
  </div>

  <h3><strong>Description</strong></h3>

  <div class="show-clown-container">
   <p class="clown-paragraphe" ><%= @clown.personal_info %></p>

    <div class="show-clown-form-container">
      <%= simple_form_for [@clown, @booking], class:"show-clown-form", id:"toto" do |f| %>
        <%= f.input :start_date, as: :date %>
        <%= f.input :end_date, as: :date %>
        <p><%= @clown.price %>€/h</p>
        <%= f.submit "Je réserve", class:"btn-form btn-danger" %>
      <% end %>
    </div>
  </div>

  <p class="confetti"></p>


  <div class="comm">
    <h3><strong>Commentaires / Reviews</strong></h3>
    <br>
    <div class="review">
      <p> Un clown compétent, drôle et discret ! Prêt à surprendre nos invités dans sa magnifique robe blanche <p class="note"><i class="fas fa-star"></i>4,6</p></p>
    </div>
    <br>
    <div class="review">
      <p> Parfait dans son rôle, conforme à sa description et aux photos.<p class="note"><i class="fas fa-star"></i>5</p></p>
    </div>
  </div>

<br>
<br>
<br>

<%= link_to clown_path(@clown),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
<button class="delete-btn">Delete</button>
<% end %>

<%= link_to edit_clown_path(@clown) do %>
<button class="delete-btn">Update</button>
<% end %>


<br>
<br>
<br>

</div>

<div class ="footer">
  <div class="card-media">
	  <h1>Suivez-nous !</h1>
	  <ul>
		  <li><a href="https://twitter.com/home" target="_blank"class="logo-socialmedia"><i class="fab fa-twitter"></i></a></li>
		  <li><a href="https://instagram.com" target="_blank" class="logo-socialmedia"><i class="fab fa-instagram"></i></a></li>
		  <li><a href="https://facebook.com" target="_blank" class="logo-socialmedia"><i class="fab fa-facebook-f"></i></a></li>
		  <li><a href="http://linkedin.com/in/gabriel-lauzier-759241184" target="_blank" class="logo-socialmedia"><i class="fab fa-linkedin-in"></i></a></li>
	  </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmilesToRent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4dd5ac52f7.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/confetti-js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "navbar" >
<div>
<%= link_to root_path do %>
<%= image_tag "SmilesForRent.png", class: "clown_logo" %>
<% end %>

<h1 class ="smile_name">SmilesForRent</h1>
</div>

<%= link_to new_clown_path do %>
<button class="create-btn">create a clown</button>
<% end %>


<%= form_tag(search_path, method: :get, class: "search-form") do %>
  <%= text_field_tag(:query, params[:query], placeholder: "Rechercher...") %>
  <button type="submit" class="search-button">
    <i class="fa-solid fa-magnifying-glass" style="color: #FFFFFF;"></i>
  </button>
<% end %>

<%= link_to profile_path do %>
<div class = "user_profile_card">
        <% if current_user %>
        <% if current_user.photo %>
          <%= image_tag current_user.photo, class: "profile_pic" %>
      <% else %>
        <%= image_tag "default.jpg", class: "profile_pic" %>
      <% end %>
      <% end %>
    </div>
<% end %>

</div>

<br>
<br>
<br>
<br>

<div class = "category_clown">

<div>
<%= image_tag "birthday.jpg" %>
<h3>Anniversaire</h3>
</div>

<div>
<%= image_tag "conférence.jpg" %>
<h3>Conférence</h3>
</div>


<div>
<%= image_tag "horreur.jpg" %>
<h3>Horreur</h3>
</div>


<div>
<%= image_tag "hopital_clown.jpg" %>
<h3>Hôpital</h3>
</div>

<div>
<%= image_tag "diner_clown.jpg" %>
<h3>Dîner</h3>
</div>

<div>
<%= image_tag "wedding.jpg" %>
<h3>Mariage</h3>
</div>

</div>

<br>
<br>
<br>

<h2 class="home-h2">Nos Clowns</h2>

<br>
<br>
<br>

<div class="card-container">
  <% @clowns.each do |clown| %>
    <%= content_tag :div, class: 'card' do %>
      <%= link_to clown_path(clown), class: 'card-link' do %>
        <%= content_tag :div, class: 'card-content' do %>
        <% if clown.photos.attached?%>
          <%= cl_image_tag clown.photos.first.key, height: 400, width: 500, crop: :fill %>
        <% end %>
<div class="name-cate-loca-price">
<div class="name-cate">
          <h2 class="card-title"><%= clown.username %></h2>
          <p class="card-info card-cate"><%= clown.category %></p>
</div>
<div class="loca-price">
          <p class="card-info card-loca"><%= clown.localisation %></p>
          <p class="card-info card-price"><%= clown.price %>€/h</p>
</div>
</div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

</div>

<div class ="footer">
<div class="card-media">
	<h1>Suivez-nous !</h1>
	<ul>
		<li><a href="https://twitter.com/home" target="_blank"class="logo-socialmedia"><i class="fab fa-twitter"></i></a></li>
		<li><a href="https://instagram.com" target="_blank" class="logo-socialmedia"><i class="fab fa-instagram"></i></a></li>
		<li><a href="https://facebook.com" target="_blank" class="logo-socialmedia"><i class="fab fa-facebook-f"></i></a></li>
		<li><a href="http://linkedin.com/in/gabriel-lauzier-759241184" target="_blank" class="logo-socialmedia"><i class="fab fa-linkedin-in"></i></a></li>
	</ul>
 </div>
</div>

app/views/pages/profile.html.erb
<div class = "navbar" >
  <div>
  <%= link_to root_path do %>
  <%= image_tag "SmilesForRent.png", class: "clown_logo" %>
  <% end %>

  <h1 class ="smile_name">SmilesForRent</h1>
</div>

<%= form_tag(search_path, method: :get, class: "search-form") do %>
  <%= text_field_tag(:query, params[:query], placeholder: "Rechercher...") %>
  <button type="submit" class="search-button">
    <i class="fa-solid fa-magnifying-glass" style="color: #FFFFFF;"></i>
  </button>
<% end %>


</div>

<div class = "container_profile">

<div class = "row1">

  <div class ="profile-card" >

    <div class = "user_profile_card">
        <% if current_user %>
        <% if current_user.photo %>
          <%= image_tag current_user.photo, class: "pic_profile_card" %>
      <% else %>
        <%= image_tag "default.jpg", class: "pic_profile_card" %>
      <% end %>
        <h3 class="profile_name"><%= current_user.username %></h3>
      <% end %>
    </div>

      <div class ="infos_profile_card">
        <p class = "avis"> 30 avis</p>
        <p>----------</p>
        <p class = "clown"> 8 clowns</p>
      </div>
  </div>

  <div class = "user_info_page">
    <h1>A propos</h1>
      <div class = "infos-haut">
        <p> Localisation</p>
        <p> e-mail</p>
        <p> Billing</p>
      </div>
      <div class = "infos-bas">
        <p> Address</p>
        <p> Infos</p>
        <p> Career</p>
      </div>
  </div>
</div>

  <div class = "row2">

    <div class = "historique">

      <h1>Mon historique</h1>

      <div class="clowns-historique-cards">
        <% current_user.bookings.each do |booking| %>
          <div class="booked_clown">
          <br>
            <%= image_tag booking.clown.photos.first, class: "clown_pic" %>
            <p class="clown"><%= booking.clown.username %></p>
          </div>
        <% end %>
      </div>

    </div>

    </div>

  </div>

</div>

<div class ="footer">
<div class="card-media">
	<h1>Suivez-nous !</h1>
	<ul>
		<li><a href="https://twitter.com/home" target="_blank"class="logo-socialmedia"><i class="fab fa-twitter"></i></a></li>
		<li><a href="https://instagram.com" target="_blank" class="logo-socialmedia"><i class="fab fa-instagram"></i></a></li>
		<li><a href="https://facebook.com" target="_blank" class="logo-socialmedia"><i class="fab fa-facebook-f"></i></a></li>
		<li><a href="http://linkedin.com/in/gabriel-lauzier-759241184" target="_blank" class="logo-socialmedia"><i class="fab fa-linkedin-in"></i></a></li>
	</ul>
 </div>
</div>